name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run 2.11 tests
      run: ./mill examples[2.11.12].test
    - name: Run 2.12 tests
      run: ./mill examples[2.12.7].test
    - name: Run 2.13 tests
      run: ./mill examples[2.13.2].test